FROM node:alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --silent

COPY . /app

ARG REACT_APP_NAVER_CLIENT_ID
ARG REACT_APP_NAVER_CLIENT_SECRET
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_GOOGLE_CLIENT_SECRET
ARG REACT_APP_KAKAO_REST_API_KEY
ARG REACT_APP_KAKAO_CLIENT_SECRET
ARG REACT_APP_API_URL
ARG REACT_APP_FRONT_URL
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_KAKAOMAP_KEY

ENV REACT_APP_NAVER_CLIENT_ID=${REACT_APP_NAVER_CLIENT_ID}
ENV REACT_APP_NAVER_CLIENT_SECRET=${REACT_APP_NAVER_CLIENT_SECRET}
ENV REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
ENV REACT_APP_GOOGLE_CLIENT_SECRET=${REACT_APP_GOOGLE_CLIENT_SECRET}
ENV REACT_APP_KAKAO_REST_API_KEY=${REACT_APP_KAKAO_REST_API_KEY}
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV REACT_APP_FRONT_URL=${REACT_APP_FRONT_URL}
ENV REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
ENV REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
ENV REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
ENV REACT_APP_KAKAOMAP_KEY=${REACT_APP_KAKAOMAP_KEY}

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
