name: Frontend build and deploy

on:
  push:
    branches:
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load environment variables from .env
    run: |
      set -o allexport
      source .env
      set +o allexport

      - name: Frontend Dockerfile build with environment variables
    run: |
      docker build $(grep -v '^#' .env | sed 's/^/--build-arg /') -t ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user .

      - name: Push Frontend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and run
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST_IP }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ "$(sudo docker ps -a -q -f name=cc-frontend-user)" ]; then
              sudo docker rm -f cc-frontend-user
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user
            fi          
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user         
            sudo docker run -d -p 80:80 --name cc-frontend-user --env-file /home/ubuntu/frontend/.env ${{ secrets.DOCKERHUB_USERNAME }}/cc-frontend-user
